GridLayout:
    cols : 1
    rows : 4
    Button:
        text: 'GameMode'
        background_color: (0, 99, 71, 0.5)
        n_press: root.gamemode()
    Button:
        text: 'ScoreBoard'
        background_color: (0, 99, 71, 0.5)
        on_press: app.scoreboard()
    Button:
        text: 'Settings'
        background_color: (0, 99, 71, 0.5)
        on_press: app.settings()
    Button:
        text: 'Exit'
        background_color: (0, 99, 71, 0.5)
        on_press: app.exitapp()